language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
  - git config user.name "tjumoon"
  - git config user.email "simon_yang@aliyun.com"
  - sed -i "s/__GH_TOKEN__/${GH_TOKEN}/" _config.yml
  - sed -i "s/__CODING_TOKEN__/${CODING_TOKEN}/" _config.yml

script:
  - hexo clean
  - hexo g

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "tjumoon"
#   - git config user.email "simon_yang@aliyun.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
after_success:
  - hexo deploy

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/tjumoon/tjumoon.github.io.git
